import React from 'react';
import { PortfolioDirection } from '../types';

interface ConceptBoardProps {
  data: PortfolioDirection;
  moodImage: string | null;
}

const ConceptBoard: React.FC<ConceptBoardProps> = ({ data, moodImage }) => {
  return (
    <div className="w-full max-w-6xl mx-auto grid grid-cols-1 lg:grid-cols-2 gap-12 p-8 animate-in fade-in duration-1000">
      
      {/* Left: Textual Concept */}
      <div className="space-y-8 flex flex-col justify-center order-2 lg:order-1">
        <div className="space-y-2">
          <span className="text-xs font-bold tracking-[0.3em] text-stone-500 uppercase">Project Title</span>
          <h1 className="text-5xl md:text-7xl font-serif text-white leading-tight">
            {data.title}
          </h1>
        </div>

        <div className="space-y-4 border-l border-stone-800 pl-6">
          <p className="text-stone-300 font-serif text-lg leading-relaxed italic">
            "{data.concept_statement}"
          </p>
        </div>

        <div className="grid grid-cols-2 gap-8 pt-6">
           <div>
             <h4 className="text-xs font-bold tracking-[0.2em] text-stone-500 uppercase mb-3">Aesthetic Keys</h4>
             <ul className="space-y-1">
               {data.aesthetic_keywords.map((kw, i) => (
                 <li key={i} className="text-stone-300 font-sans text-sm border-b border-stone-900 py-1">{kw}</li>
               ))}
             </ul>
           </div>
           <div>
             <h4 className="text-xs font-bold tracking-[0.2em] text-stone-500 uppercase mb-3">Palette</h4>
             <p className="text-stone-400 text-sm leading-relaxed">
               {data.color_palette_description}
             </p>
           </div>
        </div>
      </div>

      {/* Right: Visual Mood */}
      <div className="relative order-1 lg:order-2 h-[500px] w-full bg-stone-900 overflow-hidden shadow-2xl border border-stone-800 group">
        {moodImage ? (
          <>
            <img 
              src={moodImage} 
              alt="Generated Mood" 
              className="w-full h-full object-cover opacity-90 transition-transform duration-[3s] ease-in-out group-hover:scale-105"
            />
            <div className="absolute inset-0 bg-gradient-to-t from-stone-950 via-transparent to-transparent opacity-60"></div>
          </>
        ) : (
           <div className="w-full h-full flex items-center justify-center text-stone-600 font-serif italic">
             Generating vision...
           </div>
        )}
        
        <div className="absolute bottom-4 right-4 text-right">
           <p className="text-[10px] uppercase tracking-widest text-stone-400">Visual Identity</p>
           <p className="text-white font-serif italic text-sm">Generated by Gemini</p>
        </div>
      </div>

    </div>
  );
};

export default ConceptBoard;
